### ISSUE TITLE
Vulnerability in secret generation

### ISSUE THREAD

**Issue by ggozad** [placepay/python-googauth#1]
Hey,
Your secret generation is broken. 
`return base64.b32encode(hexhash)[:length]` will produce a base32 encoding of a hex string (instead of bytes) resulting always in half the bit strength. So if we say use the default of 16 chars, the result will be a 16-digit base32 string. Decoding this by `base64.b32decode(secret)` will produce a 10-digit hex string. This is 40bits instead of 80bits which is what you should be getting.

**Comment by zachhuff386** [comment]
Thanks, fixed in last commit.
